
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-03T19:59:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "13bc039e805e8a2cd8d816b939362b40018ea8ef",
 "version": "1.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
